version: 2
updates:
  - package-ecosystem: github-actions
    versioning-strategy: widen
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      weekly-updates:
        patterns:
          - "*"
