name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['**']
  workflow_dispatch:

permissions:
  packages: read

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-D warnings'

jobs:
  test-nightly:
    name: Test Linux (${{ matrix.container }})

    strategy:
      matrix:
        include:
          - runs-on: ubuntu-24.04
            container: ci-ubuntu-cross-amd64
          - runs-on: ubuntu-24.04-arm
            container: ci-ubuntu-arm64
          - runs-on: ubuntu-24.04
            container: ci-alpine-amd64
          - runs-on: ubuntu-24.04
            container: ci-opensuse-amd64
          - runs-on: ubuntu-24.04-arm
            container: ci-opensuse-arm64

      fail-fast: false

    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 10

    container:
      image: ghcr.io/wild-linker/wild/${{ matrix.container }}:sha-b58cc74a969f3f81c8a01b5d626fa850e3d39c38

    steps:
      # https://github.com/actions/runner/issues/3210
      - run: echo "$PATH" >> "$GITHUB_PATH"
        if: ${{ contains(matrix.container, 'opensuse') }}
      - run: echo "WILD_TEST_CONFIG=test-config-ci.toml" >> $GITHUB_ENV
      - run: echo "WILD_TEST_CROSS=all" >> $GITHUB_ENV
        if: ${{ contains(matrix.container, '-cross') }}
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: wild-linker/action@latest
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-${{ matrix.container }}-${{ matrix.runs-on }}
      - run: cargo build --profile ci --workspace --no-default-features
      - run: WILD_TEST_CROSS=$WILD_TEST_CROSS cargo test --profile ci --workspace

  riscv-build:
    name: Build Linux (RISC-V)
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    container:
      image: ghcr.io/wild-linker/wild/ci-ubuntu-cross-amd64:sha-b58cc74a969f3f81c8a01b5d626fa850e3d39c38
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
        id: rust-toolchain
        with:
          targets: riscv64gc-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - run: cp -f .cargo/config.toml.cross-riscv .cargo/config.toml
      - run: cargo build --target riscv64gc-unknown-linux-gnu

  loongarch64-build:
    name: Build Linux (LoongArch64)
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    container:
      image: ghcr.io/wild-linker/wild/ci-ubuntu-cross-amd64:sha-b58cc74a969f3f81c8a01b5d626fa850e3d39c38
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
        id: rust-toolchain
        with:
          targets: loongarch64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - run: cp -f .cargo/config.toml.cross-loongarch64 .cargo/config.toml
      - run: cargo build --target loongarch64-unknown-linux-gnu

  ppc64le-build:
    name: Build Linux (PPC64LE)
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    container:
      image: ghcr.io/wild-linker/wild/ci-ubuntu-cross-amd64:sha-b58cc74a969f3f81c8a01b5d626fa850e3d39c38
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
        id: rust-toolchain
        with:
          targets: powerpc64le-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - run: cp -f .cargo/config.toml.cross-ppc64le .cargo/config.toml
      - run: cargo build --target powerpc64le-unknown-linux-gnu

  # TODO: Switch this to use our own container rather than apt-get installing stuff. The use of
  # gcc-multilib is the problematic part since it conflicts with packages we install in our cross
  # container. Ideally, it shouldn't be needed if builds are configured correctly.
  wasip1-build:
    name: Build wasip1
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    container:
      image: ubuntu:25.10
    steps:
      - name: Install xz-utils
        run: apt-get update && apt-get install -y xz-utils
      - name: Setup Wasmtime
        uses: bytecodealliance/actions/wasmtime/setup@v1
        with:
          version: '43.0.0'
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - run: apt-get install --update -y build-essential gcc gcc-multilib clang curl
      - uses: dtolnay/rust-toolchain@stable
        id: rust-toolchain
        with:
          targets: wasm32-wasip1
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --target wasm32-wasip1
      - run: cp -f .cargo/config.toml.cross-wasm32p1 .cargo/config.toml
      # -p libwild prevents integration tests from running. they depend on
      # spawning processes, which isn't supported on wasi.
      - run: cargo test --profile ci -p libwild --target wasm32-wasip1

  wasm-test:
    name: Test Wasm
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
        id: rust-toolchain
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get update && sudo apt-get install -y wabt lld wasi-libc
      - uses: taiki-e/install-action@v2
        with:
          tool: wasm-tools
      - name: Setup Wasmtime
        uses: bytecodealliance/actions/wasmtime/setup@v1
        with:
          version: '43.0.0'
      - run: cargo test --features wasm -- wasm

  macho-build:
    name: Test Mach-O (AArch64)
    runs-on: macos-latest
    timeout-minutes: 10
    env:
      WILD_TEST_IGNORE_FORMAT: "1" # Checked by other jobs
    steps:
      - run: brew install lld
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
        id: rust-toolchain
      - uses: Swatinem/rust-cache@v2
        with:
          env-vars: ImageVersion
      - run: cargo build --profile ci --workspace --no-default-features
      - run: cargo test --profile ci --workspace --features macho

  windows-build:
    name: Build Windows (x86_64)
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
        id: rust-toolchain
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --profile ci --workspace --no-default-features

  minimal-versions:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    container:
      image: ghcr.io/wild-linker/wild/ci-ubuntu-amd64:sha-b58cc74a969f3f81c8a01b5d626fa850e3d39c38
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
        id: rust-toolchain
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack,cargo-minimal-versions,taplo
      - uses: Swatinem/rust-cache@v2
      - run: cargo minimal-versions --direct test --profile ci

  clippy:
    name: Clippy
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      # This is where we check that we're not using features from a more recent rust version. When
      # updating this, please also update workspace.package.rust-version in `Cargo.toml`.
      - uses: dtolnay/rust-toolchain@1.94.0
        id: rust-toolchain
        with:
          components: clippy
      - uses: wild-linker/action@latest
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-targets --workspace --target x86_64-unknown-linux-gnu

  rustfmt:
    name: Check formatting
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  yamlfmt:
    name: yamlfmt
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26.0'
          cache: false
      - run: go install github.com/google/yamlfmt/cmd/yamlfmt@v0.21.0
      - run: echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      - run: yamlfmt -lint .

  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Spell Check Repo
        uses: crate-ci/typos@v1.48.0

  calc-matrix:
    name: Find Nix checks
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    outputs:
      matrix: ${{ steps.calc-matrix.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v35
        with:
          nix_on_tmpfs: true

      - name: Calculate check
        id: calc-matrix
        run: |
          set -euo pipefail
          matrix=$(nix flake show --json | jq -c '.checks."x86_64-linux"|keys_unsorted')
          echo "Matrix: $matrix"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  nix-checks:
    needs:
      - calc-matrix
    strategy:
      fail-fast: false
      matrix:
        check: ${{ fromJson(needs.calc-matrix.outputs.matrix) }}
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    name: Nix/${{ matrix.check }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v35

      - name: Restore Nix store
        uses: nix-community/cache-nix-action/restore@v7
        id: cache
        with:
          primary-key: ${{ runner.os }}-${{ hashFiles( 'flake.lock', 'Cargo.lock') }}

      - name: Run ${{ matrix.check }}
        run: nix build .#checks.x86_64-linux.${MATRIX_CHECK} -L --show-trace
        env:
          MATRIX_CHECK: ${{ matrix.check }}
