name: Run external tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

permissions:
  packages: read

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  external-tests:
    name: Run mold tests
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    container:
      image: "ghcr.io/wild-linker/wild/ci-ubuntu-cross-amd64:sha-f05d76af90966595dd3606a0ebf2a0db8281843f"
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          submodules: recursive
      - uses: Swatinem/rust-cache@v2
      - name: Check regressions
        run: WILD_TEST_CROSS=all cargo test --features mold_tests external_test_suites/mold -- --skip expect_failure
      - name: Check tests that should fail still fail
        run: WILD_TEST_CROSS=all cargo test --features mold_tests expect_failure
